spring:
  datasource:
    url: jdbc:mysql://localhost:3306/commerce_db?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
#    url: jdbc:h2:mem:test
#    driver-class-name: org.h2.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create


logging:
  level.org:
    hibernate:
      sql: DEBUG

